# Plugins
gems:             ['jekyll-paginate', 'jekyll-gist', 'jekyll-github-metadata']

# Dependencies
# highlighter:      rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Permalinks
permalink:        pretty

# Setup
title:            Kinact
tagline:          Kinase Activity Toolbox
description:      "Toolbox to score kinase activities based on phosphoproteomics data"
#url:              https://github.com/saezlab/kinact
baseurl:          /kinact/

author:
  name:           'Jakob Wirbel'

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/saezlab/kinact
